spring.application.name=comment-service
server.port=9025

#localhost - since we work with it via Docker container
spring.datasource.username=${GA_MY_POSTGRES_USER}
spring.datasource.password=${GA_MY_POSTGRES_PASSWORD}
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.url=${GA_MY_POSTGRES_ENDPOINT}/comments_db
spring.datasource.driver-class-name=org.postgresql.Driver


# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true