server.port=9040
spring.application.name=news-service
spring.task.execution.pool.core-size=8
spring.task.execution.pool.max-size=16
spring.task.execution.pool.queue-capacity=100

# ====== UPLOAD SIZE LIMITS ======
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

#localhost - since we work with it via Docker container
spring.datasource.username=${GA_MY_POSTGRES_USER}
spring.datasource.password=${GA_MY_POSTGRES_PASSWORD}
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.url=${GA_MY_POSTGRES_ENDPOINT:jdbc:postgresql://localhost:5400/news_db}
spring.datasource.driver-class-name=org.postgresql.Driver


# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# MinIO Configuration // secret as a password, access as a login
minio.endpoint=${GA_MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${GA_MINIO_ACCESS}
minio.secret-key=${GA_MINIO_SECRET}
minio.bucket-name=${GA_MINIO_BUCKET_NAME}

#REDIS

spring.data.redis.host=localhost
spring.data.redis.port=6300
spring.data.redis.timeout=5s


