spring.application.name=user-service
server.port=9060

#localhost - since we work with it via Docker container
spring.datasource.url=jdbc:postgresql://localhost:5400/postgres
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#localhost - since we work with it via Docker container
spring.data.redis.host=localhost
spring.data.redis.port=6300
spring.data.redis.timeout=5s
spring.data.redis.password=${REDIS_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
