spring.application.name=gratitude-service
server.port=9020

#localhost - since we work with it via Docker container
spring.datasource.username=${MY_POSTGRES_USER:postgres}
spring.datasource.password=${MY_POSTGRES_PASSWORD:postgres}
spring.datasource.url=jdbc:postgresql://localhost:5400/${MY_POSTGRES_DB:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

#localhost - since we work with it via Docker container
spring.data.redis.host=localhost
spring.data.redis.port=6300
spring.data.redis.timeout=5s
spring.data.redis.password=${REDIS_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true