server:
  port: 4050

spring:
  application:
    name: email-service
  kafka:
    bootstrap-servers: localhost:9092  # address where Kafka is run
    template:
      default-topic: "notification_topic"
    consumer:
      group-id: "notificationId"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.type.mapping: "ru.kashtanov.order_service.dto.OrderPlacedEvent:ru.kashtanov.notification_service.dto.OrderPlacedEvent"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
